// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package partial

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func TypeIcon(pokemonType string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if pokemonType == "electric" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<img src=\"./../static/icons/electric.svg\" alt=\"type-icon\" style=\"width:100%;height:100%;object-fit:contain;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if pokemonType == "water" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<img src=\"./../static/icons/water.svg\" alt=\"type-icon\" style=\"width:100%;height:100%;object-fit:contain;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if pokemonType == "fire" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<img src=\"./../static/icons/fire.svg\" alt=\"type-icon\" style=\"width:100%;height:100%;object-fit:contain;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if pokemonType == "grass" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<img src=\"./../static/icons/grass.svg\" alt=\"type-icon\" style=\"width:100%;height:100%;object-fit:contain;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if pokemonType == "normal" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<img src=\"./../static/icons/normal.svg\" alt=\"type-icon\" style=\"width:100%;height:100%;object-fit:contain;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
